const FETCH_PRODUCTS_REQUESTS = 'FETCH_PRODUCTS_REQUESTS';
const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
const FETCH_PRODUCTS_FAILUR = 'FETCH_PRODUCTS_FAILUR';

export {
    FETCH_PRODUCTS_REQUESTS,
    FETCH_PRODUCTS_SUCCESS,
    FETCH_PRODUCTS_FAILUR
}